-- MySQL Script generated by MySQL Workbench
-- Thu May 23 02:17:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vehiculos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vehiculos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculos` (
   `idVehiculos` INT(11) NOT NULL AUTO_INCREMENT,
   `marca` VARCHAR(255) NOT NULL,
   `modelo` VARCHAR(255) NOT NULL,
   `anio` YEAR (4) NOT NULL,
   `generacion` VARCHAR(225) NOT NULL,
   `motor` VARCHAR(255) NOT NULL,
   `tipo_combustible` VARCHAR(50) NOT NULL,
   `consumo_km_l` FLOAT NOT NULL,
   `tipo_traccion` VARCHAR(50) NOT NULL,
   `tipo_carroceria` VARCHAR(50) NOT NULL,
   `numero_plazas` INT(2) NOT NULL,
   `ruta_imagen` VARCHAR(255),
   PRIMARY KEY (`idVehiculos`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `idCuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL UNIQUE,
  `contrasenia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Historial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Historial` (
  `idHistorial` INT(11) NOT NULL AUTO_INCREMENT,
  `idCuenta` INT(11) NOT NULL,
  `idVehiculos` INT(11) NOT NULL,
  `fechaVisualizacion` DATETIME(6) NOT NULL,
  `borrarHistorial` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idHistorial`),
  CONSTRAINT `FK_Cuenta_Historial`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Vehiculos_Historial`
    FOREIGN KEY (`idVehiculos`)
    REFERENCES `mydb`.`Vehiculos` (`idVehiculos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favoritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favoritos` (
  `idFavoritos` INT(11) NOT NULL AUTO_INCREMENT,
  `idCuenta` INT(11) NOT NULL,
  `idVehiculos` INT(11) NOT NULL,
  `agregados` DATETIME(6) NOT NULL,
  `quitarFavorito` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idFavoritos`),
  CONSTRAINT `FK_Cuenta_Favoritos`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Vehiculos_Favoritos`
    FOREIGN KEY (`idVehiculos`)
    REFERENCES `mydb`.`Vehiculos` (`idVehiculos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;